version: "3"

services:

  concourse-db:
    image: postgres:9.5
    networks:
    - concourse
    environment:
    - POSTGRES_DB=concourse
    - POSTGRES_USER=concourse
    - POSTGRES_PASSWORD="Fp.<}t9yf.?"
    - PGDATA=/database
    deploy:
      replicas: 1

  concourse-web:
    image: concourse/concourse
    privileged: true
    command: web
    networks:
    - concourse
    ports:
    - 8080:8080
    volumes:
      - ./keys/web:/concourse-keys
    environment:
    - CONCOURSE_BASIC_AUTH_USERNAME=concourse
    - CONCOURSE_BASIC_AUTH_PASSWORD=changeme
    - CONCOURSE_EXTERNAL_URL="${CONCOURSE_EXTERNAL_URL}"
    - CONCOURSE_POSTGRES_DATA_SOURCE="postgres://concourse:changeme@concourse-db:5432/concourse?sslmode=disable"
    deploy:
      replicas: 1

  concourse-worker:
    image: concourse/concourse
    privileged: true
    command: worker
    networks:
    - concourse
    volumes:
    - ./keys/worker:/concourse-keys
    environment:
    - CONCOURSE_TSA_HOST=concourse-web

networks:
  concourse:
