version: '3.1'

services:
  concourse-db:
    image: postgres:9.5
    networks:
    - concourse
    environment:
    - POSTGRES_DB=concourse
    - POSTGRES_USER=concourse
    - POSTGRES_PASSWORD=M3sseyP233
    - PGDATA=/database
    deploy:
      mode: replicated
      replicas: 1

  concourse-web:
    image: concourse/concourse
    privileged: true
    command: web
    networks:
    - concourse
    ports:
    - 8080:8080
    volumes:
      - ./keys/web:/concourse-keys
    environment:
    - CONCOURSE_BASIC_AUTH_USERNAME=concourse
    - CONCOURSE_BASIC_AUTH_PASSWORD=M3sseyP233
#    - CONCOURSE_EXTERNAL_URL="${CONCOURSE_EXTERNAL_URL}"
    - CONCOURSE_POSTGRES_DATA_SOURCE=postgres://concourse:M3sseyP233@concourse-db:5432/concourse?sslmode=disable
    deploy:
      mode: replicated
      replicas: 1

  concourse-worker:
    image: concourse/concourse
    privileged: true
    command: worker
    networks:
    - concourse
    volumes:
    - ./keys/worker:/concourse-keys
    environment:
    - CONCOURSE_TSA_HOST=concourse-web
    deploy:
      mode: replicated
      replicas: 2

networks:
  concourse:
